In [1]:
import pandas as pd
print("Pandas working")

Pandas working

In [2]:
import pandas as pd
df = pd.read_csv("../data/sample_emails.csv")
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        8 non-null      int64
 1   sender    8 non-null      object
 2   subject   8 non-null      object
 3   body      8 non-null      object
 4   priority  8 non-null      object
 5   label     8 non-null      object
dtypes: int64(1), object(5)
memory usage: 516.0+ bytes

In [4]:
print(df.columns)

Index(['id', 'sender', 'subject', 'body', 'priority', 'label'], dtype='object')

In [5]:
df['body'][0]

'Dear Candidate, Congratulations! Please sign and upload your offer letter by today evening.'

In [6]:
df['priority'].value_counts()

priority
high      4
low       2
medium    2
Name: count, dtype: int64

In [7]:
df['clean_text'] = df['body'].str.lower().str.replace('[^a-zA-Z]',' ',regex=True)
df[['body','clean_text']].head()

,body,clean_text
0,"Dear Candidate, Congratulations! Please sign a...",dear candidate congratulations please sign a...
1,Flat 70% OFF on electronics. Limited period of...,flat off on electronics limited period of...
2,We detected a login attempt to your account fr...,we detected a login attempt to your account fr...
3,"In this week's edition, learn about AI agents,...",in this week s edition learn about ai agents ...
4,"Hey, long time no see! Are you free this weeke...",hey long time no see are you free this weeke...

In [8]:
print("ORIGINAL:", df['body'][0])
print("CLEANED:",  df['clean_text'][0])

ORIGINAL: Dear Candidate, Congratulations! Please sign and upload your offer letter by today evening.
CLEANED: dear candidate  congratulations  please sign and upload your offer letter by today evening