In [2]:
import pandas as pd
df = pd.read_csv("../data/sample_emails.csv")
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        8 non-null      int64
 1   sender    8 non-null      object
 2   subject   8 non-null      object
 3   body      8 non-null      object
 4   priority  8 non-null      object
 5   label     8 non-null      object
dtypes: int64(1), object(5)
memory usage: 516.0+ bytes

1.Handle Missing Values & Clean Text
2.Create a Combined Text Column (Subject + Body)
3.Simple Filtering Examples

In [5]:
df.describe(include="all")

,id,sender,subject,body,priority,label
count,8.00000,8,8,8,8,8
unique,NaN,8,8,8,3,7
top,NaN,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,work
freq,NaN,1,1,1,4,2
mean,4.50000,NaN,NaN,NaN,NaN,NaN
std,2.44949,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN
25%,2.75000,NaN,NaN,NaN,NaN,NaN
50%,4.50000,NaN,NaN,NaN,NaN,NaN
75%,6.25000,NaN,NaN,NaN,NaN,NaN
max,8.00000,NaN,NaN,NaN,NaN,NaN

In [6]:
df["label"].value_counts()

label
work          2
promotion     1
important     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [7]:
df.fillna("")

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal
5,6,spam@strange-domain.ru,"You won $1,000,000!!!",Click here to claim your lottery now. Do not s...,high,spam
6,7,manager@company.com,Project Update Required,Please share the status update of your project...,high,work
7,8,training@lms.com,Reminder: Complete Mandatory Training,Your mandatory security awareness training is ...,medium,work

In [8]:
df = df.fillna("")
df['subject'] = df['subject'].str.lower().str.strip()
df['body'] = df['body'].str.lower().str.strip()
print(df)

   id                  sender                                subject  \
0   1          hr@company.com             offer letter - please sign
1   2    noreply@shopping.com               big billion sale is live
2   3       alerts@mybank.com                  unusual login attempt
3   4     newsletter@blog.com                 weekly tech newsletter
4   5     friend123@gmail.com                   coffee this weekend?
5   6  spam@strange-domain.ru                  you won $1,000,000!!!
6   7     manager@company.com                project update required
7   8        training@lms.com  reminder: complete mandatory training

                                                body priority       label
0  dear candidate, congratulations! please sign a...     high   important
1  flat 70% off on electronics. limited period of...      low   promotion
2  we detected a login attempt to your account fr...     high    security
3  in this week's edition, learn about ai agents,...      low  newsletter
4  hey, long time no see! are you free this weeke...   medium    personal
5  click here to claim your lottery now. do not s...     high        spam
6  please share the status update of your project...     high        work
7  your mandatory security awareness training is ...   medium        work

In [9]:
df['combined'] = df['subject'] + " " + df['body']
print(df)

   id                  sender                                subject  \
0   1          hr@company.com             offer letter - please sign
1   2    noreply@shopping.com               big billion sale is live
2   3       alerts@mybank.com                  unusual login attempt
3   4     newsletter@blog.com                 weekly tech newsletter
4   5     friend123@gmail.com                   coffee this weekend?
5   6  spam@strange-domain.ru                  you won $1,000,000!!!
6   7     manager@company.com                project update required
7   8        training@lms.com  reminder: complete mandatory training

                                                body priority       label  \
0  dear candidate, congratulations! please sign a...     high   important
1  flat 70% off on electronics. limited period of...      low   promotion
2  we detected a login attempt to your account fr...     high    security
3  in this week's edition, learn about ai agents,...      low  newsletter
4  hey, long time no see! are you free this weeke...   medium    personal
5  click here to claim your lottery now. do not s...     high        spam
6  please share the status update of your project...     high        work
7  your mandatory security awareness training is ...   medium        work

                                            combined
0  offer letter - please sign dear candidate, con...
1  big billion sale is live flat 70% off on elect...
2  unusual login attempt we detected a login atte...
3  weekly tech newsletter in this week's edition,...
4  coffee this weekend? hey, long time no see! ar...
5  you won $1,000,000!!! click here to claim your...
6  project update required please share the statu...
7  reminder: complete mandatory training your man...

In [10]:
offer_only = df[df['combined'].str.contains("offer")]
print(df)
print("\nOffer Messages:")
print(offer_only)

   id                  sender                                subject  \
0   1          hr@company.com             offer letter - please sign
1   2    noreply@shopping.com               big billion sale is live
2   3       alerts@mybank.com                  unusual login attempt
3   4     newsletter@blog.com                 weekly tech newsletter
4   5     friend123@gmail.com                   coffee this weekend?
5   6  spam@strange-domain.ru                  you won $1,000,000!!!
6   7     manager@company.com                project update required
7   8        training@lms.com  reminder: complete mandatory training

                                                body priority       label  \
0  dear candidate, congratulations! please sign a...     high   important
1  flat 70% off on electronics. limited period of...      low   promotion
2  we detected a login attempt to your account fr...     high    security
3  in this week's edition, learn about ai agents,...      low  newsletter
4  hey, long time no see! are you free this weeke...   medium    personal
5  click here to claim your lottery now. do not s...     high        spam
6  please share the status update of your project...     high        work
7  your mandatory security awareness training is ...   medium        work

                                            combined
0  offer letter - please sign dear candidate, con...
1  big billion sale is live flat 70% off on elect...
2  unusual login attempt we detected a login atte...
3  weekly tech newsletter in this week's edition,...
4  coffee this weekend? hey, long time no see! ar...
5  you won $1,000,000!!! click here to claim your...
6  project update required please share the statu...
7  reminder: complete mandatory training your man...

Offer Messages:
   id                sender                     subject  \
0   1        hr@company.com  offer letter - please sign
1   2  noreply@shopping.com    big billion sale is live

                                                body priority      label  \
0  dear candidate, congratulations! please sign a...     high  important
1  flat 70% off on electronics. limited period of...      low  promotion

                                            combined
0  offer letter - please sign dear candidate, con...
1  big billion sale is live flat 70% off on elect...

In [11]:
important_only = df[df['label'].str.contains("important")]
print(important_only)

   id          sender                     subject  \
0   1  hr@company.com  offer letter - please sign

                                                body priority      label  \
0  dear candidate, congratulations! please sign a...     high  important

                                            combined
0  offer letter - please sign dear candidate, con...

In [12]:
df.shape

(8, 7)

In [13]:
df.isnull().sum()

id          0
sender      0
subject     0
body        0
priority    0
label       0
combined    0
dtype: int64

In [14]:
print(df['subject'][0])

offer letter - please sign

In [15]:
df['priority'].value_counts()

priority
high      4
low       2
medium    2
Name: count, dtype: int64

In [16]:
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label', 'combined'], dtype='object')

In [17]:
df['clean_text'] = df['body'].str.lower().str.replace('[^a-zA-Z]',"",regex=True)
df[['body','clean_text']].head()

,body,clean_text
0,"dear candidate, congratulations! please sign a...",dearcandidatecongratulationspleasesignanduploa...
1,flat 70% off on electronics. limited period of...,flatoffonelectronicslimitedperiodoffervisitour...
2,we detected a login attempt to your account fr...,wedetectedaloginattempttoyouraccountfromanewde...
3,"in this week's edition, learn about ai agents,...",inthisweekseditionlearnaboutaiagentslanggrapha...
4,"hey, long time no see! are you free this weeke...",heylongtimenoseeareyoufreethisweekendforcoffee

In [18]:
from collections import Counter

all_words = " ".join(df['clean_text']).split()
word_freq = Counter(all_words)
word_freq.most_common(3)

[('dearcandidatecongratulationspleasesignanduploadyourofferletterbytodayevening',
  1),
 ('flatoffonelectronicslimitedperiodoffervisitourstorenow', 1),
 ('wedetectedaloginattempttoyouraccountfromanewdeviceifthiswasnotyoupleaseresetyourpassword',
  1)]

In [19]:
all_words_text = "".join(df['clean_text'])

In [21]:
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label', 'combined',
       'clean_text'],
      dtype='object')

In [22]:
df['clean_text'] = df['body'].str.lower().str.replace('[^a-zA-Z]','',regex=True)
df[['body','clean_text']].head()

,body,clean_text
0,"dear candidate, congratulations! please sign a...",dearcandidatecongratulationspleasesignanduploa...
1,flat 70% off on electronics. limited period of...,flatoffonelectronicslimitedperiodoffervisitour...
2,we detected a login attempt to your account fr...,wedetectedaloginattempttoyouraccountfromanewde...
3,"in this week's edition, learn about ai agents,...",inthisweekseditionlearnaboutaiagentslanggrapha...
4,"hey, long time no see! are you free this weeke...",heylongtimenoseeareyoufreethisweekendforcoffee

In [23]:
all_words_text = " ".join(df['clean_text'])

In [24]:
words = all_words_text.split()

In [25]:
len(words)

8

In [27]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Collecting nltk
  Downloading nltk-3.9.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in c:\users\pc-lenovo\appdata\roaming\python\python313\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\pc-lenovo\appdata\roaming\python\python313\site-packages (from nltk) (1.5.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\pc-lenovo\appdata\roaming\python\python313\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\pc-lenovo\appdata\roaming\python\python313\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\pc-lenovo\appdata\roaming\python\python313\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.2-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.5 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.5 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.5 MB 491.9 kB/s eta 0:00:03
   ------------- -------------------------- 0.5/1.5 MB 491.9 kB/s eta 0:00:03
   -------------------- ------------------- 0.8/1.5 MB 582.0 kB/s eta 0:00:02
   -------------------- ------------------- 0.8/1.5 MB 582.0 kB/s eta 0:00:02
   --------------------------- ------------ 1.0/1.5 MB 640.0 kB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 724.8 kB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 724.8 kB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 724.8 kB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 724.8 kB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 724.8 kB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 724.8 kB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 724.8 kB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 724.8 kB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 724.8 kB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 377.1 kB/s  0:00:04
Installing collected packages: nltk
Successfully installed nltk-3.9.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
filtered_words = [w for w in words if w not in stop_words]

[nltk_data] Downloading package stopwords to C:\Users\PC-
[nltk_data]     LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [29]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
filtered_words = [w for w in words if w not in stop_words]

[nltk_data] Downloading package stopwords to C:\Users\PC-
[nltk_data]     LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [30]:
# Without NLTK 
["please", "approve","the","project","status","update","urgently"]

#With NLTK
["approv","project","status","updat","urgent"]

['approv', 'project', 'status', 'updat', 'urgent']