In [3]:
import pandas as pd

df = pd.read_csv("../data/milestone1_output.csv")
df.head()

,id,sender,subject,body,priority,triage_label,clean_text,triage,triage_match
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,your invoice of inr 25515.09 is due on 2025-12...,notify_human,\binvoice\b
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,"hello team, please find the attached weekly re...",respond_or_act,\battached\b
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,"hello team, please find the attached weekly re...",respond_or_act,\battached\b

In [4]:
df = pd.read_csv("../data/sample_emails_with_triage_200.csv")

In [1]:
import pandas as pd

df = pd.read_csv("../data/sample_emails_with_triage_200.csv")
df.head()

,id,sender,subject,body,priority,triage_label
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond

In [2]:
# Select 100 test emails

eval_df = df.sample(100,random_state=42)
eval_df = eval_df.reset_index(drop=True)
eval_df.head()

,id,sender,subject,body,priority,triage_label
0,96,no-reply@service.com,Weekly Newsletter,Your order #3634 has been shipped and is expec...,low,ignore
1,16,news@techblog.com,Payment Overdue,"Hi, don't miss our sale with discounts up to 7...",low,notify_human
2,31,news@techblog.com,Weekly Newsletter,Notice: Your account will be locked unless ver...,high,notify_human
3,159,no-reply@service.com,Welcome to Service,Reminder: The client meeting is scheduled at 9...,low,respond
4,129,sales@shop.com,Invoice Due,Your order #6464 has been shipped and is expec...,low,respond

In [1]:
from langsmith import Client
client = Client()

ModuleNotFoundError: No module named 'langsmith'

In [2]:
pip install langsmith

^C
Note: you may need to restart the kernel to use updated packages.

In [4]:
!pip install langsmith

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: langsmith in c:\users\pantla\appdata\roaming\python\python313\site-packages (0.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from langsmith) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from langsmith) (3.11.5)
Requirement already satisfied: packaging>=23.2 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from langsmith) (25.0)
Requirement already satisfied: pydantic<3,>=1 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from langsmith) (2.12.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from langsmith) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from langsmith) (2.32.5)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from langsmith) (0.12.0)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from langsmith) (0.25.0)
Requirement already satisfied: anyio in c:\users\pantla\appdata\roaming\python\python313\site-packages (from httpx<1,>=0.23.0->langsmith) (4.12.0)
Requirement already satisfied: certifi in c:\users\pantla\appdata\roaming\python\python313\site-packages (from httpx<1,>=0.23.0->langsmith) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\pantla\appdata\roaming\python\python313\site-packages (from httpx<1,>=0.23.0->langsmith) (1.0.9)
Requirement already satisfied: idna in c:\users\pantla\appdata\roaming\python\python313\site-packages (from httpx<1,>=0.23.0->langsmith) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from pydantic<3,>=1->langsmith) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from pydantic<3,>=1->langsmith) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from pydantic<3,>=1->langsmith) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from pydantic<3,>=1->langsmith) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from requests>=2.0.0->langsmith) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from requests>=2.0.0->langsmith) (2.6.2)

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
from langsmith import Client
client = Client()

In [7]:
# Define the Judge Prompt

judge_prompt = """You are an evaluator. Compare the model output with the ideal answer.

Check:
1. Action correctness
2. Tone correctness

Give score:
1 = correct
0 = incorrect
"""

In [13]:
def evaluate(agent_output, ideal_action, ideal_tone):
    if(
        agent_output["action"] == ideal_action
        and agent_output["tone"] == ideal_tone
    ):
        return 1
    else:
        return 0

In [14]:
agent_output = {
    "action": "notify",
    "tone": "urgent"
}

In [15]:
ideal_action = "notify"
ideal_tone = "urgent"

In [16]:
score = evaluate(agent_output, ideal_action, ideal_tone)
score

1

In [15]:
import pandas as pd

df = pd.read_csv("../data/sample_emails_with_triage_200.csv")
df.head()

,id,sender,subject,body,priority,triage_label
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond

In [ ]:
def email_assistant(body):
    text = email_text.lower()
    
    if "urgent" in text or "submit" in text or "deadline" in text:
        return {"action": "notify", "tone": "urgent"}
    
    elif "thank you" in text or "thanks" in text:
        return {"action": "ignore", "tone": "polite"}
    
    else:
        return {"action": "respond", "tone": "neutral"}

In [20]:
# Run the evaluation on sample data

scores = []

for _, row in df.iterrows():
    prediction = email_assistant(row["body"])
    score = evaluate(
        prediction,
        row["ideal_action"],
        row["ideal_tone"]
    )
    scores.append(score)

accuracy = (sum(scores)/len(scores))*100
accuracy

NameError: name 'evaluate' is not defined