In [22]:
import pandas as pd

In [23]:
path = "../data/email_evaluation_swethanand-sangamreddi.csv"
df = pd.read_csv(path)
df.head()

,email_text,expected_action,expected_tone
0,"Hi Swetha, this is a reminder about the team m...",notify,polite
1,Please confirm your availability for the proje...,respond,polite
2,The meeting scheduled for today has been postp...,notify,neutral
3,This is a reminder to submit the weekly report...,notify,urgent
4,Kindly join the review call at 3 PM using the ...,notify,polite

In [24]:
def email_assistant(email_text):
    text = email_text.lower()
    if "urgent" in text or "submit" in text or "deadline" in text:
        return "notify", "urgent"
    elif "thank you" in text or "thanks" in text:
        return "ignore", "neutral"
    else:
        return "respond", "neutral"

In [25]:
df.columns

Index(['email_text', 'expected_action', 'expected_tone'], dtype='object')

In [26]:
df[['predicted_action', 'predicted_tone']] = df['email_text'].apply(lambda x: pd.Series(email_assistant(x)))

In [27]:
df[['email_text', 'predicted_action', 'predicted_tone']].head()

,email_text,predicted_action,predicted_tone
0,"Hi Swetha, this is a reminder about the team m...",respond,neutral
1,Please confirm your availability for the proje...,respond,neutral
2,The meeting scheduled for today has been postp...,respond,neutral
3,This is a reminder to submit the weekly report...,notify,urgent
4,Kindly join the review call at 3 PM using the ...,respond,neutral

In [28]:
df['action_correct'] = df['predicted_action'] == df['expected_action']
df['correct_tone'] = df['predicted_tone'] == df['expected_tone']

In [29]:
df[['action_correct', 'correct_tone']].mean()

action_correct    0.383838
correct_tone      0.575758
dtype: float64

In [30]:
action_accuracy = df['action_correct'].mean() * 100
tone_accuracy = df['correct_tone'].mean() * 100

print(f"Action Prediction Accuracy: {action_accuracy:.2f}%")
print(f"Tone Prediction Accuracy: {tone_accuracy:.2f}%")

Action Prediction Accuracy: 38.38%
Tone Prediction Accuracy: 57.58%