In [1]:
import pandas as pd

file_path = '/Users/nitishrmaladakar/Desktop/infosys/infosys-langgraph-email-assistant-group2/data/email_evaluation_dataset_Nitish_R_Maladakar.csv' 
df = pd.read_csv(file_path)
print("Data loaded successfully!")
display(df.head())

Data loaded successfully!

,id,email_text,expected_action,expected_tone
0,1,"Hi team, just a reminder that the Q3 marketing...",respond,neutral
1,2,Invoice #2024-001 is now overdue by 5 days. Pl...,notify,urgent
2,3,Congratulations! You have been shortlisted for...,respond,polite
3,4,"Hey, are we still on for lunch today? Let me k...",respond,casual
4,5,Weekly Newsletter: Top 10 trends in AI this we...,ignore,neutral

In [2]:
df = pd.read_csv(r"/Users/nitishrmaladakar/Desktop/infosys/infosys-langgraph-email-assistant-group2/data/email_evaluation_dataset_Nitish_R_Maladakar.csv")
print(df.head(50))

    id                                         email_text expected_action  \
0    1  Hi team, just a reminder that the Q3 marketing...         respond
1    2  Invoice #2024-001 is now overdue by 5 days. Pl...          notify
2    3  Congratulations! You have been shortlisted for...         respond
3    4  Hey, are we still on for lunch today? Let me k...         respond
4    5  Weekly Newsletter: Top 10 trends in AI this we...          ignore
5    6  Urgent: The production server is down. We need...          notify
6    7  Can you please send me the syllabus for the up...         respond
7    8  Automatic Reply: I am currently out of the off...          ignore
8    9  Your subscription to Spotify has been successf...          ignore
9   10  Attached is the final report for the project. ...         respond
10  11  Reminder: Your dentist appointment is tomorrow...          notify
11  12  Please find the attached invoice for the recen...          notify
12  13  Quick question - what is the wifi password for...         respond
13  14  Dear Student, the deadline for submitting your...          notify
14  15  50% OFF on all shoes! Limited time offer. Shop...          ignore
15  16  Could you review my pull request when you get ...         respond
16  17  Meeting canceled: Project Kickoff. We will res...          ignore
17  18  I'm running 10 minutes late to the standup. St...          ignore
18  19  Security Alert: A new device signed into your ...          notify
19  20  Happy Birthday! wishing you a fantastic year a...          ignore
20  21  Can you help me debug this React Native error?...         respond
21  22  Your package has been delivered to the front d...          notify
22  23  Please updated your contact information in the...         respond
23  24  Do not reply to this email. This is a system g...          ignore
24  25         Invitation: Code Review Session @ Thu 3pm.         respond
25  26  Hi, I am interested in your research regarding...         respond
26  27  Your credit card ending in 1234 was declined. ...          notify
27  28  Don't forget to submit your timesheet for this...          notify
28  29  FW: The client wants to change the scope of th...          notify
29  30  Welcome to the team! We are excited to have yo...         respond
30  31    New assignment uploaded: Data Structures Lab 4.          notify
31  32   Can you share the link to the Figma design file?         respond
32  33  Refund processed: $29.99 has been credited to ...          ignore
33  34  Are you free for a quick call to discuss the h...         respond
34  35  Google Calendar Reminder: Dentist Appointment ...          ignore
35  36  Please approve the budget request for the new ...         respond
36  37  Hi, I noticed a typo on the landing page. Just...         respond
37  38           Your Uber ride is arriving in 2 minutes.          ignore
38  39  Action Required: Verify your email address to ...         respond
39  40  Hey, did you see the game last night? It was i...          ignore
40  41  The library books are due tomorrow. Please ret...          notify
41  42  Request for Leave: I would like to take next M...         respond
42  43     Your monthly bank statement is ready for view.          ignore
43  44   Can we postpone our 1:1 to later this afternoon?         respond
44  45    Warning: High disk usage detected on Server 01.          notify
45  46  Thank you for your order. Your tracking number...          ignore
46  47  Class is cancelled today due to the professor ...          notify
47  48  Looking for a 27-inch monitor recommendations....         respond
48  49  Final Call: Register for the workshop before s...          ignore
49  50  Hey, I think I left my charger at your desk. D...         respond

   expected_tone
0        neutral
1         urgent
2         polite
3         casual
4        neutral
5         urgent
6         polite
7        neutral
8        neutral
9        neutral
10       neutral
11       neutral
12       neutral
13        polite
14       neutral
15       neutral
16       neutral
17       neutral
18        urgent
19        polite
20       neutral
21       neutral
22       neutral
23       neutral
24       neutral
25        polite
26        urgent
27       neutral
28        urgent
29        polite
30       neutral
31       neutral
32       neutral
33       neutral
34       neutral
35        urgent
36        polite
37       neutral
38        urgent
39        casual
40       neutral
41       neutral
42       neutral
43       neutral
44        urgent
45       neutral
46       neutral
47       neutral
48        urgent
49       neutral

In [8]:
import re

def clean_email_text(text):
    if not isinstance(text, str):
        return ""
    text = text.lower() 

    text = text.replace('\n', ' ').strip()
    
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    
    return text

df['Clean_text'] = df['email_text'].apply(clean_email_text)


print("Clean_text column created successfully!")
display(df[['email_text', 'Clean_text']].head())

Clean_text column created successfully!

,email_text,Clean_text
0,"Hi team, just a reminder that the Q3 marketing...",hi team just a reminder that the q marketing s...
1,Invoice #2024-001 is now overdue by 5 days. Pl...,invoice is now overdue by days please proces...
2,Congratulations! You have been shortlisted for...,congratulations you have been shortlisted for ...
3,"Hey, are we still on for lunch today? Let me k...",hey are we still on for lunch today let me kno...
4,Weekly Newsletter: Top 10 trends in AI this we...,weekly newsletter top trends in ai this week ...

In [11]:
def email_assistant(email_text):
    text = email_text.lower()
    
    urgent_keywords = [
        "urgent", "overdue", "security", "breach", "declined", 
        "failed", "immediate", "server", "crash", "alert"
    ]
    ignore_keywords = [
        "newsletter", "automatic reply", "subscription", "deal", 
        "offer", "tracking", "system generated", "no reply", "marketing"
    ]
    if any(word in text for word in urgent_keywords):
        return "notify", "urgent"

    elif any(word in text for word in ignore_keywords):
        return "ignore", "neutral"
    
    elif "thank you" in text or "congratulations" in text:
        return "respond", "polite"

    else :
        return "respond", "neutral"

# Apply assistant function to the dataset

In [19]:
results = df['email_text'].apply(email_assistant)

# Create separate output columns

In [ ]:


df[['predicted_action', 'predicted_tone']] = pd.DataFrame(results.tolist(), index=df.index)


print(df[['email_text', 'predicted_action', 'predicted_tone']].head())

                                          email_text predicted_action  \
0  Hi team, just a reminder that the Q3 marketing...           ignore
1  Invoice #2024-001 is now overdue by 5 days. Pl...           notify
2  Congratulations! You have been shortlisted for...          respond
3  Hey, are we still on for lunch today? Let me k...          respond
4  Weekly Newsletter: Top 10 trends in AI this we...           ignore

  predicted_tone
0        neutral
1         urgent
2         polite
3        neutral
4        neutral

# Compare predictions with expected values

In [17]:
df['action_correct'] = df['predicted_action'] == df['expected_action']
df['tone_correct'] = df['predicted_tone'] == df['expected_tone']

# Calculate accuracy

In [18]:



action_accuracy = df['action_correct'].mean() * 100
tone_accuracy = df['tone_correct'].mean() * 100

print(f"Action Accuracy: {action_accuracy:.2f}%")
print(f"Tone Accuracy: {tone_accuracy:.2f}%")


print(df[['expected_action', 'predicted_action', 'action_correct']].head())

Action Accuracy: 57.00%
Tone Accuracy: 70.00%
  expected_action predicted_action  action_correct
0         respond           ignore           False
1          notify           notify            True
2         respond          respond            True
3         respond          respond            True
4          ignore           ignore            True

# Error Analysis

In [ ]:

errors = df[df['action_correct'] == False]

print("Number of Action Errors:", len(errors))
print("\n--- Error Samples ---")
print(errors[['email_text', 'expected_action', 'predicted_action']].head(10))

Number of Action Errors: 43

--- Error Samples ---
                                           email_text expected_action  \
0   Hi team, just a reminder that the Q3 marketing...         respond
10  Reminder: Your dentist appointment is tomorrow...          notify
11  Please find the attached invoice for the recen...          notify
13  Dear Student, the deadline for submitting your...          notify
16  Meeting canceled: Project Kickoff. We will res...          ignore
17  I'm running 10 minutes late to the standup. St...          ignore
19  Happy Birthday! wishing you a fantastic year a...          ignore
21  Your package has been delivered to the front d...          notify
27  Don't forget to submit your timesheet for this...          notify
28  FW: The client wants to change the scope of th...          notify

   predicted_action
0            ignore
10          respond
11          respond
13          respond
16          respond
17          respond
19          respond
21          respond
27          respond
28          respond

In [ ]:
import os


df.to_csv('../data/milestone2_output_nitish.csv', index=False)

print("File saved successfully.")

File saved successfully.

## `1. Which type of emails were hardest to classify?`

Emails that implied urgency without using specific keywords like 'urgent' or 'deadline' (e.g., 'My screen is black', 'Invoice overdue'). Also, polite emails that required action (e.g., 'Thank you, but can you fix this?') were often misclassified as 'Ignore'.


## `2. Why did your rules fail in some cases?`

The rule-based approach is too rigid . It relies entirely on exact keyword matching. It cannot understand context, synonyms (like 'asap' vs 'urgent'), or the main reason behind a email.


## `3. How could an LLM improve this process?`

An LLM understands real meaning and context. It can detect urgency from tone even if specific keywords are missing and can distinguish between a polite sign-off ('Thank you') and a polite request ('Thank you for doing this, please reply').